/**
 * The built-in local model rows, overlaid on the catalog when it lacks them.
 */
import type { WorkbenchModel } from "../types.ts";

export function defaultLocalWorkbenchModels(): WorkbenchModel[] {
  return [
    {
      slug: "qwen3.6:35b-a3b",
      displayName: "Qwen3.6 35B (MoE)",
      provider: "ollama",
      api: "openai-completions",
      baseUrl: "http://localhost:11434/v1",
      tier: 0,
      costInput: 0,
      costOutput: 0,
      capabilities: [
        "text",
        "code",
        "reasoning",
        "vision",
        "tools",
        "long-context",
      ],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      modality: "local",
      architecture: "moe",
      totalParamsB: 36.0,
      activeParamsB: 3.0,
      recommendedQuant: "Q4_K_M",
      residentRamGiB: 24.0,
      reasoningEffortControl: false,
    },
    {
      slug: "muse-glimmer:30b",
      displayName: "Muse Glimmer 30B",
      provider: "ollama",
      api: "openai-completions",
      baseUrl: "http://localhost:11434/v1",
      tier: 0,
      costInput: 0,
      costOutput: 0,
      capabilities: [
        "text",
        "code",
        "reasoning",
        "vision",
        "tools",
        "long-context",
      ],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      modality: "local",
      architecture: "dense",
      totalParamsB: 27.9,
      activeParamsB: 27.9,
      recommendedQuant: "Q4_K_M",
      residentRamGiB: 23.0,
      reasoningEffortControl: true,
    },
    {
      slug: "mistral-small:24b-instruct-2501-q4_K_M",
      displayName: "Mistral Small 24B",
      provider: "ollama",
      api: "openai-completions",
      baseUrl: "http://localhost:11434/v1",
      tier: 0,
      costInput: 0,
      costOutput: 0,
      capabilities: ["text", "code", "reasoning", "tools"],
      contextWindow: 32768,
      maxOutputTokens: 8192,
      modality: "local",
      architecture: "dense",
      totalParamsB: 23.6,
      activeParamsB: 23.6,
      recommendedQuant: "Q4_K_M",
      residentRamGiB: 15.0,
      reasoningEffortControl: false,
    },
    {
      slug: "deepseek-r1:32b",
      displayName: "DeepSeek-R1 Distill 32B",
      provider: "ollama",
      api: "openai-completions",
      baseUrl: "http://localhost:11434/v1",
      tier: 0,
      costInput: 0,
      costOutput: 0,
      capabilities: ["text", "code", "reasoning", "thinking"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      modality: "local",
      architecture: "dense",
      totalParamsB: 32.8,
      activeParamsB: 32.8,
      recommendedQuant: "Q4_K_M",
      residentRamGiB: 22.0,
      reasoningEffortControl: false,
    },
    {
      slug: "laguna-xs-2.1",
      displayName: "Laguna XS 2.1",
      provider: "ollama",
      api: "openai-completions",
      baseUrl: "http://localhost:11434/v1",
      tier: 0,
      costInput: 0,
      costOutput: 0,
      capabilities: [
        "text",
        "code",
        "reasoning",
        "tools",
        "thinking",
        "long-context",
      ],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      modality: "local",
      architecture: "moe",
      totalParamsB: 33.4,
      activeParamsB: 3.0,
      recommendedQuant: "Q4_K_M",
      residentRamGiB: 20.0,
      reasoningEffortControl: false,
    },
    {
      slug: "gemma4:26b",
      displayName: "Gemma 4 26B (MoE)",
      provider: "ollama",
      api: "openai-completions",
      baseUrl: "http://localhost:11434/v1",
      tier: 0,
      costInput: 0,
      costOutput: 0,
      capabilities: [
        "text",
        "reasoning",
        "vision",
        "tools",
        "thinking",
        "long-context",
      ],
      contextWindow: 262144,
      maxOutputTokens: 8192,
      modality: "local",
      architecture: "moe",
      totalParamsB: 26.0,
      activeParamsB: 3.8,
      recommendedQuant: "Q4_K_M",
      residentRamGiB: 17.0,
      reasoningEffortControl: false,
    },
    {
      slug: "gemma4:e2b",
      displayName: "Gemma 4 2B (dev)",
      provider: "ollama",
      api: "openai-completions",
      baseUrl: "http://localhost:11434/v1",
      tier: 0,
      costInput: 0,
      costOutput: 0,
      capabilities: ["text", "reasoning"],
      contextWindow: 131072,
      maxOutputTokens: 8192,
      modality: "local",
      architecture: "dense",
      totalParamsB: 5.1,
      activeParamsB: 5.1,
      recommendedQuant: "Q4_K_M",
      residentRamGiB: 7.0,
      reasoningEffortControl: false,
    },
  ];
}

export function withDefaultLocalWorkbenchModels(
  models: WorkbenchModel[],
): WorkbenchModel[] {
  const defaultModels = defaultLocalWorkbenchModels()
    .filter((model) =>
      !models.some((existing) => existing.slug === model.slug)
    );
  return [...defaultModels, ...models];
}
