-- Add execution and architecture profile columns to models table.
-- Allows local models to declare architecture, parameter scale, quantization,
-- and RAM residency, alongside a boolean flag for reasoning effort control.

ALTER TABLE models
  ADD COLUMN architecture VARCHAR(16) NULL AFTER capabilities,
  ADD COLUMN total_params_b DECIMAL(6, 2) NULL AFTER architecture,
  ADD COLUMN active_params_b DECIMAL(6, 2) NULL AFTER total_params_b,
  ADD COLUMN recommended_quant VARCHAR(64) NULL AFTER active_params_b,
  ADD COLUMN resident_ram_gib DECIMAL(5, 2) NULL AFTER recommended_quant,
  ADD COLUMN reasoning_effort_control BOOLEAN NOT NULL DEFAULT FALSE AFTER resident_ram_gib;

-- Backfill declared architecture and residency metadata for existing models.
UPDATE models SET active = TRUE, architecture = 'moe', total_params_b = 30.50, active_params_b = 3.00, recommended_quant = '8bit', resident_ram_gib = 32.00 WHERE slug = 'mlx-community/Qwen3-Coder-30B-A3B-Instruct-8bit';
UPDATE models SET architecture = 'dense', total_params_b = 4.00, active_params_b = 4.00, recommended_quant = '8bit', resident_ram_gib = 5.00 WHERE slug = 'mlx-community/Qwen3.5-4B-8bit';
UPDATE models SET active = FALSE, architecture = 'dense', total_params_b = 33.40, active_params_b = 33.40, recommended_quant = 'Q4_K_M', resident_ram_gib = 24.00 WHERE slug = 'laguna-xs.2';
UPDATE models SET active = FALSE, display_name = 'Gemma 4 8B', architecture = 'dense', total_params_b = 8.00, active_params_b = 8.00, recommended_quant = 'Q4_K_M', resident_ram_gib = 10.00, context_window = 131072, capabilities = '["text","reasoning","vision","tools","thinking"]' WHERE slug = 'gemma4';
UPDATE models SET active = TRUE, architecture = 'dense', total_params_b = 5.10, active_params_b = 5.10, recommended_quant = 'Q4_K_M', resident_ram_gib = 7.00 WHERE slug = 'gemma4:e2b';
UPDATE models SET active = FALSE, architecture = 'moe', total_params_b = 30.50, active_params_b = 3.00, recommended_quant = 'Q4_K_M', resident_ram_gib = 20.00, context_window = 262144, capabilities = '["text","code","reasoning","chat","long-context"]' WHERE slug = 'qwen3:30b-a3b';
UPDATE models SET architecture = 'dense', total_params_b = 32.80, active_params_b = 32.80, recommended_quant = 'Q4_K_M', resident_ram_gib = 20.00, context_window = 40960, active = FALSE WHERE slug = 'qwen3:32b';
UPDATE models SET architecture = 'moe', total_params_b = 284.00, active_params_b = 13.00 WHERE slug = 'deepseek/deepseek-v4-flash';
UPDATE models SET architecture = 'moe', total_params_b = 550.00, active_params_b = 55.00 WHERE slug = 'nvidia/nemotron-3-ultra-550b-a55b';
UPDATE models SET architecture = 'moe' WHERE slug IN ('tencent/hy3', 'z-ai/glm-5.2');
UPDATE models SET active = TRUE, architecture = 'dense', total_params_b = 32.80, active_params_b = 32.80, recommended_quant = 'Q4_K_M', resident_ram_gib = 22.00 WHERE slug = 'deepseek-r1:32b';
UPDATE models SET active = TRUE, architecture = 'dense', total_params_b = 23.60, active_params_b = 23.60, recommended_quant = 'Q4_K_M', resident_ram_gib = 15.00 WHERE slug = 'mistral-small:24b-instruct-2501-q4_K_M';
UPDATE models SET active = TRUE, architecture = 'dense', total_params_b = 27.90, active_params_b = 27.90, recommended_quant = 'Q4_K_M', resident_ram_gib = 23.00, reasoning_effort_control = TRUE WHERE slug = 'muse-glimmer:30b';
UPDATE models SET active = TRUE, architecture = 'moe', total_params_b = 36.00, active_params_b = 3.00, recommended_quant = 'Q4_K_M', resident_ram_gib = 24.00 WHERE slug = 'qwen3.6:35b-a3b';

-- Upsert newly cataloged local models.
INSERT INTO models (
    slug,
    display_name,
    provider,
    api,
    base_url,
    tier,
    context_window,
    max_output_tokens,
    cost_input,
    cost_output,
    cost_cache_read,
    cost_cache_write,
    reasoning,
    capabilities,
    architecture,
    total_params_b,
    active_params_b,
    recommended_quant,
    resident_ram_gib,
    reasoning_effort_control,
    active
) VALUES
    (
        'deepseek-r1:32b',
        'DeepSeek-R1 Distill 32B',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        131072,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","code","reasoning","thinking"]',
        'dense',
        32.80,
        32.80,
        'Q4_K_M',
        22.00,
        FALSE,
        TRUE
    ),
    (
        'gpt-oss-120b',
        'GPT-OSS 120B',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        131072,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","code","reasoning","tools","long-context"]',
        'moe',
        117.00,
        5.10,
        'MXFP4',
        64.00,
        FALSE,
        FALSE
    ),
    (
        'gemma4:26b',
        'Gemma 4 26B (MoE)',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        262144,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","reasoning","vision","tools","thinking","long-context"]',
        'moe',
        26.00,
        3.80,
        'Q4_K_M',
        17.00,
        FALSE,
        TRUE
    ),
    (
        'laguna-xs-2.1',
        'Laguna XS 2.1',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        262144,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","code","reasoning","tools","thinking","long-context"]',
        'moe',
        33.40,
        3.00,
        'Q4_K_M',
        20.00,
        FALSE,
        TRUE
    ),
    (
        'mistral-small:24b-instruct-2501-q4_K_M',
        'Mistral Small 24B',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        32768,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","code","reasoning","tools"]',
        'dense',
        23.60,
        23.60,
        'Q4_K_M',
        15.00,
        FALSE,
        TRUE
    ),
    (
        'mistral-small-4-119b-a6b',
        'Mistral Small 4 119B',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        262144,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","code","reasoning","vision","tools","long-context"]',
        'moe',
        119.00,
        6.50,
        'Q4_K_M',
        62.00,
        FALSE,
        FALSE
    ),
    (
        'muse-glimmer:30b',
        'Muse Glimmer 30B',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        131072,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","code","reasoning","vision","tools","long-context"]',
        'dense',
        27.90,
        27.90,
        'Q4_K_M',
        23.00,
        TRUE,
        TRUE
    ),
    (
        'qwen3.5-122b-a10b',
        'Qwen3.5 122B (MoE)',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        262144,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","code","reasoning","long-context"]',
        'moe',
        122.00,
        10.00,
        'Q4_K_M',
        64.00,
        FALSE,
        FALSE
    ),
    (
        'qwen3.6:35b-a3b',
        'Qwen3.6 35B (MoE)',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        262144,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","code","reasoning","vision","tools","long-context"]',
        'moe',
        36.00,
        3.00,
        'Q4_K_M',
        24.00,
        FALSE,
        TRUE
    ),
    (
        'qwen3-coder-next-80b-a3b',
        'Qwen3-Coder-Next 80B',
        'ollama',
        'openai-completions',
        'http://localhost:11434/v1',
        0,
        262144,
        8192,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        TRUE,
        '["text","code","reasoning","tools","long-context"]',
        'moe',
        80.00,
        3.00,
        'Q5_K_M',
        42.00,
        FALSE,
        FALSE
    )
ON DUPLICATE KEY UPDATE
    display_name = VALUES(display_name),
    provider = VALUES(provider),
    api = VALUES(api),
    base_url = VALUES(base_url),
    tier = VALUES(tier),
    context_window = VALUES(context_window),
    `max_output_tokens` = VALUES(`max_output_tokens`),
    cost_input = VALUES(cost_input),
    cost_output = VALUES(cost_output),
    cost_cache_read = VALUES(cost_cache_read),
    cost_cache_write = VALUES(cost_cache_write),
    reasoning = VALUES(reasoning),
    capabilities = VALUES(capabilities),
    architecture = VALUES(architecture),
    total_params_b = VALUES(total_params_b),
    active_params_b = VALUES(active_params_b),
    recommended_quant = VALUES(recommended_quant),
    resident_ram_gib = VALUES(resident_ram_gib),
    reasoning_effort_control = VALUES(reasoning_effort_control),
    active = VALUES(active);
