-- Refresh frontier hosted models and pricing across Anthropic, OpenAI, Google, and xAI.
-- Synchronizes direct vendor production lineups with consensus pricing, context windows,
-- and reasoning controls as of August 2026.

-- 1. Deactivate superseded / retired frontier model entries.
UPDATE models SET active = FALSE WHERE slug IN (
    'claude-opus-4-5',
    'claude-opus-4-8',
    'claude-sonnet-4-6',
    'gemini-2.5-flash',
    'gemini-2.5-pro',
    'gemini-3.5-flash',
    'gpt-5.4',
    'gpt-5.4-mini',
    'gpt-5.5'
);

-- 2. Update existing active frontier models with current consensus pricing and limits.
UPDATE models SET
    display_name = 'Claude Fable 5',
    tier = 2,
    context_window = 1000000,
    max_output_tokens = 128000,
    cost_input = 10.000000,
    cost_output = 50.000000,
    cost_cache_read = 1.000000,
    cost_cache_write = 12.500000,
    reasoning = TRUE,
    capabilities = '["text","code","reasoning","vision","tools","thinking","long-context"]',
    reasoning_effort_control = FALSE,
    active = TRUE
WHERE slug = 'claude-fable-5';

UPDATE models SET
    display_name = 'Claude Haiku 4.5',
    tier = 1,
    context_window = 200000,
    max_output_tokens = 64000,
    cost_input = 1.000000,
    cost_output = 5.000000,
    cost_cache_read = 0.100000,
    cost_cache_write = 1.250000,
    reasoning = TRUE,
    capabilities = '["text","code","vision","tools"]',
    reasoning_effort_control = FALSE,
    active = TRUE
WHERE slug = 'claude-haiku-4-5-20251001';

UPDATE models SET
    display_name = 'Gemini 3.1 Pro',
    tier = 2,
    context_window = 1048576,
    max_output_tokens = 65536,
    cost_input = 2.000000,
    cost_output = 12.000000,
    cost_cache_read = 0.200000,
    cost_cache_write = 0.000000,
    reasoning = TRUE,
    capabilities = '["text","code","reasoning","vision","tools","thinking","long-context"]',
    reasoning_effort_control = TRUE,
    active = TRUE
WHERE slug = 'gemini-3.1-pro-preview';

-- 3. Upsert newly cataloged frontier models for Anthropic, OpenAI, Google, and xAI.
INSERT INTO models (
    slug,
    display_name,
    provider,
    api,
    base_url,
    tier,
    context_window,
    max_output_tokens,
    cost_input,
    cost_output,
    cost_cache_read,
    cost_cache_write,
    reasoning,
    capabilities,
    architecture,
    total_params_b,
    active_params_b,
    recommended_quant,
    resident_ram_gib,
    reasoning_effort_control,
    active
) VALUES
    (
        'claude-opus-5',
        'Claude Opus 5',
        'anthropic',
        'anthropic-messages',
        'https://api.anthropic.com',
        2,
        1000000,
        128000,
        5.000000,
        25.000000,
        0.500000,
        6.250000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'claude-sonnet-5',
        'Claude Sonnet 5',
        'anthropic',
        'anthropic-messages',
        'https://api.anthropic.com',
        1,
        1000000,
        128000,
        2.000000,
        10.000000,
        0.200000,
        2.500000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'gpt-5.6-sol',
        'GPT-5.6 Sol',
        'openai',
        'openai-completions',
        'https://api.openai.com/v1',
        2,
        1050000,
        128000,
        5.000000,
        30.000000,
        0.500000,
        6.250000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'gpt-5.6-terra',
        'GPT-5.6 Terra',
        'openai',
        'openai-completions',
        'https://api.openai.com/v1',
        1,
        1050000,
        128000,
        2.000000,
        12.000000,
        0.200000,
        2.500000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'gpt-5.6-luna',
        'GPT-5.6 Luna',
        'openai',
        'openai-completions',
        'https://api.openai.com/v1',
        1,
        1050000,
        128000,
        0.200000,
        1.200000,
        0.020000,
        0.250000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'gpt-5.3-codex',
        'GPT-5.3 Codex',
        'openai',
        'openai-completions',
        'https://api.openai.com/v1',
        1,
        400000,
        128000,
        1.750000,
        14.000000,
        0.175000,
        0.000000,
        TRUE,
        '["text","code","reasoning","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        FALSE
    ),
    (
        'gemini-3.7-flash',
        'Gemini 3.7 Flash',
        'google',
        'google-generative-ai',
        'https://generativelanguage.googleapis.com',
        1,
        1048576,
        65536,
        0.750000,
        3.750000,
        0.075000,
        0.000000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'gemini-3.6-flash',
        'Gemini 3.6 Flash',
        'google',
        'google-generative-ai',
        'https://generativelanguage.googleapis.com',
        1,
        1048576,
        65536,
        0.750000,
        3.750000,
        0.075000,
        0.000000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'gemini-3.5-flash-lite',
        'Gemini 3.5 Flash-Lite',
        'google',
        'google-generative-ai',
        'https://generativelanguage.googleapis.com',
        1,
        1048576,
        65536,
        0.300000,
        2.500000,
        0.030000,
        0.000000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'grok-4.6',
        'Grok 4.6',
        'xai',
        'openai-completions',
        'https://api.x.ai/v1',
        2,
        500000,
        65536,
        2.000000,
        6.000000,
        0.500000,
        0.000000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'grok-4.3',
        'Grok 4.3',
        'xai',
        'openai-completions',
        'https://api.x.ai/v1',
        1,
        1000000,
        65536,
        1.250000,
        2.500000,
        0.200000,
        0.000000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'grok-build-0.1',
        'Grok Build 0.1',
        'xai',
        'openai-completions',
        'https://api.x.ai/v1',
        1,
        256000,
        65536,
        1.000000,
        2.000000,
        0.200000,
        0.000000,
        TRUE,
        '["text","code","reasoning","tools","thinking"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        TRUE
    ),
    (
        'grok-4.5',
        'Grok 4.5',
        'xai',
        'openai-completions',
        'https://api.x.ai/v1',
        2,
        500000,
        65536,
        2.000000,
        6.000000,
        0.300000,
        0.000000,
        TRUE,
        '["text","code","reasoning","vision","tools","thinking","long-context"]',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        TRUE,
        FALSE
    )
ON DUPLICATE KEY UPDATE
    display_name = VALUES(display_name),
    provider = VALUES(provider),
    api = VALUES(api),
    base_url = VALUES(base_url),
    tier = VALUES(tier),
    context_window = VALUES(context_window),
    `max_output_tokens` = VALUES(`max_output_tokens`),
    cost_input = VALUES(cost_input),
    cost_output = VALUES(cost_output),
    cost_cache_read = VALUES(cost_cache_read),
    cost_cache_write = VALUES(cost_cache_write),
    reasoning = VALUES(reasoning),
    capabilities = VALUES(capabilities),
    architecture = VALUES(architecture),
    total_params_b = VALUES(total_params_b),
    active_params_b = VALUES(active_params_b),
    recommended_quant = VALUES(recommended_quant),
    resident_ram_gib = VALUES(resident_ram_gib),
    reasoning_effort_control = VALUES(reasoning_effort_control),
    active = VALUES(active);
